//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Forside</summary>
	[PublishedModel("forside")]
	public partial class Forside : Master
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public new const string ModelTypeAlias = "forside";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Forside, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Forside(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Citat 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("citat1")]
		public string Citat1 => this.Value<string>("citat1");

		///<summary>
		/// Citat 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("citat2")]
		public string Citat2 => this.Value<string>("citat2");

		///<summary>
		/// Citat 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("citat3")]
		public string Citat3 => this.Value<string>("citat3");

		///<summary>
		/// Citat 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("citat4")]
		public string Citat4 => this.Value<string>("citat4");

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("content")]
		public global::Newtonsoft.Json.Linq.JToken Content => this.Value<global::Newtonsoft.Json.Linq.JToken>("content");

		///<summary>
		/// Forside Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("forsideHeader")]
		public string ForsideHeader => this.Value<string>("forsideHeader");

		///<summary>
		/// Forside Header Slogan
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("forsideHeaderSlogan")]
		public string ForsideHeaderSlogan => this.Value<string>("forsideHeaderSlogan");

		///<summary>
		/// Introduktion
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("introduktion")]
		public string Introduktion => this.Value<string>("introduktion");
	}
}
