//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Medlem Item</summary>
	[PublishedModel("medlemItem")]
	public partial class MedlemItem : Master
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public new const string ModelTypeAlias = "medlemItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MedlemItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public MedlemItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Medlem Billede
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("medlemBillede")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent MedlemBillede => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("medlemBillede");

		///<summary>
		/// Medlem Navn
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("medlemNavn")]
		public string MedlemNavn => this.Value<string>("medlemNavn");

		///<summary>
		/// Medlem Rolle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("medlemRolle")]
		public string MedlemRolle => this.Value<string>("medlemRolle");

		///<summary>
		/// Medlem Uddannelse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.1")]
		[ImplementPropertyType("medlemUddannelse")]
		public string MedlemUddannelse => this.Value<string>("medlemUddannelse");
	}
}
